#include <stdio.h>
#include <wiringPi.h>

int main(void)
{
	wiringPiSetup();
	pinMode(1,OUTPUT);
	pinMode(2,OUTPUT);
	pinMode(3,OUTPUT);
	pinMode(4,OUTPUT);
	pinMode(5,OUTPUT);
	pinMode(6,OUTPUT);
	while(1)
	{
		digitalWrite(0,HIGH);
		digitalWrite(6,HIGH);
		delay(1000);
		digitalWrite(0,LOW);
		digitalWrite(6,LOW);
		delay(1000);
		digitalWrite(1,HIGH);
		digitalWrite(5,HIGH);
		delay(1000);
		digitalWrite(1,LOW);
		digitalWrite(5,LOW);
		delay(1000);
		digitalWrite(2,HIGH);
		digitalWrite(3,HIGH);
		delay(1000);
		digitalWrite(2,LOW);
		digitalWrite(3,LOW);
		delay(1000);
		digitalWrite(4,HIGH);
		delay(1000);
		digitalWrite(4,LOW);
		delay(1000);
		delay(1000);
		digitalWrite(2,HIGH);
		digitalWrite(3,HIGH);
		delay(1000);
		digitalWrite(2,LOW);
		digitalWrite(3,LOW);
		delay(1000);
		digitalWrite(1,HIGH);
		digitalWrite(5,HIGH);
		delay(1000);
		digitalWrite(1,LOW);
		digitalWrite(5,LOW);
		delay(1000);
		digitalWrite(0,HIGH);
		digitalWrite(6,HIGH);
		delay(1000);
		digitalWrite(0,LOW);
		digitalWrite(6,LOW);
	}
}
